name: tanaman_detect
description: Aplikasi deteksi penyakit tanaman untuk padi, cabai, jagung
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.12.1
  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  
  # Database
  sqflite: ^2.3.3
  path_provider: ^2.1.2
  path: ^1.9.0
  
  # State Management
  provider: ^6.1.1
  
  # Image & Camera
  image_picker: ^1.0.7

  image: ^3.2.2
  
  # Shared Preferences untuk session
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/plant_model.tflite
    - assets/models/plant_label.txt
    - assets/data/disease_data.json
    - assets/images/logo.png
    - assets/images/padi.jpg
    - assets/images/cabai.jpg
    - assets/images/jagung.jpg
    - assets/images/tomat.jpg
